### PR TITLE
Bump meck dependency.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Once merged, need to retag and bump the tag on ```basho/riak_pb```.

**Comment by seancribbs** [comment]
:+1: 2216a1b

For riak_pb, tag it 2.0.5.0, if this is going into the 2.0.5 build, otherwise 2.0.6.0.

**Comment by cmeiklejohn** [comment]
Merged and tagged release 0.8.1p5.

**Comment by cmeiklejohn** [comment]
Confused, riak_pb is currently at 2.0.0.16.  You want me to jump right to 2.0.6?

**Pull request merged**
